const fs = require('fs');
let c = fs.readFileSync('prisma/schema.prisma', 'utf8');
c = c.replace(
  /enum SystemEventType \{[\s\S]*?FORM_INFO\s*\}/,
  \enum SystemEventType {
  CALL_COMPLETED
  LEAD_CREATED
  AGENT_DEPLOYED
  CREDIT_LOW
  INTEGRATION_SYNC
  BILLING_ALERT
  CREDIT_ADDED
  CREDIT_DEDUCTED
  CREDIT_EDITED
  NOTIFICATION_CREATED
  NOTIFICATION_EDITED
  NOTIFICATION_DELETED
  AGENT_CREATED
  AGENT_EDITED
  AGENT_DELETED
  NUMBER_ASSIGNED
  NUMBER_RELEASED
  COMPANY_CREATED
  JOB_POSTED
  FORM_INFO
  USER_LOGIN
  COMPANY_EDITED
  COMPANY_DELETED
  NUMBER_EDITED
  INFRA_COST_EDITED
  INFRA_COST_TRANSFERRED
  FORM_SUBMITTED
  VERIFICATION_UPDATED
}\
);
fs.writeFileSync('prisma/schema.prisma', c);
